### ISSUE TITLE
HL Compatibility

### ISSUE THREAD

**Issue by SomeGuyWhoLovesCoding** [YanniZ06/HaxeAL-Soft#3]
I know haxe-al soft is such a good haxelib but it doesn't have to only support cpp natively. I wonder if you can add support for HashLink too!

**Comment by SomeGuyWhoLovesCoding** [comment]
``cpp.Star<T>`` is just ``Null<T>``.

**Comment by SomeGuyWhoLovesCoding** [comment]
``cpp.Float32`` is just ``Single``

**Comment by SomeGuyWhoLovesCoding** [comment]
``cpp.Reference<T>`` is just ``T``, so we can just do ``typedef Reference<T> = T;``

**Comment by SomeGuyWhoLovesCoding** [comment]
I wonder if I can make a HashLink version of ``cpp.Pointer``

**Comment by YanniZ06** [comment]
I can look into it eventually, if and when I do I might also try once more to fix up the hellish microphone stuff

**Comment by YanniZ06** [comment]
@SomeGuyWhoLovesCoding if you want to you can fork the repo and ill see to working on it, that is if you already have a planned approach
